language: node_js
node_js:
  - "4.2"
  - "4.1"
  - "4.0"
  - "0.12"
# these are required for building on node.js 4.0 / io.js v3
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
env:
  - "CXX=g++-4.8"
# end: these are required for building on node.js 4.0 / io.js v3